import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { findSecretLeaks } from './openapi.config';

/**
 * Contract tests for the committed OpenAPI artifact (T10). The artifact is
 * generated by `npm run docs:openapi` (`src/openapi/export-openapi.ts`) from
 * the real Nest application, and committed to `docs/openapi.json`. These
 * specs keep that artifact honest: a route removed from a controller (or a
 * decorator dropped) without regenerating the document turns them red.
 */

interface OpenApiOperation {
  [method: string]: unknown;
}

interface OpenApiDoc {
  openapi: string;
  info: { title: string; version: string };
  paths: Record<string, OpenApiOperation>;
  components?: {
    securitySchemes?: Record<
      string,
      { type?: string; scheme?: string; bearerFormat?: string }
    >;
  };
}

const ARTIFACT_PATH = join(process.cwd(), 'docs', 'openapi.json');

function loadDoc(): OpenApiDoc {
  if (!existsSync(ARTIFACT_PATH)) {
    throw new Error(
      'docs/openapi.json is missing — run `npm run docs:openapi` to generate it',
    );
  }
  return JSON.parse(readFileSync(ARTIFACT_PATH, 'utf8')) as OpenApiDoc;
}

/** Every active controller must contribute at least one documented path. */
const CONTROLLER_PREFIXES = [
  'auth',
  'home',
  'courses',
  'lessons',
  'enrollments',
  'orders',
  'progress',
  'projects',
  'collective',
  'marketplace',
  'search',
  'admin',
  'admin/media',
] as const;

/** A sample of real routes, cross-checked against the controllers. */
const REQUIRED_OPERATIONS: ReadonlyArray<[string, string]> = [
  ['get', '/api'],
  ['post', '/api/auth/register'],
  ['post', '/api/auth/login'],
  ['post', '/api/auth/refresh'],
  ['post', '/api/auth/logout'],
  ['get', '/api/auth/me'],
  ['get', '/api/home'],
  ['get', '/api/courses'],
  ['get', '/api/courses/{slug}'],
  ['post', '/api/courses/{id}/publish'],
  ['get', '/api/courses/{slug}/lessons'],
  ['get', '/api/lessons/{id}/video-url'],
  ['patch', '/api/lessons/{id}/reorder'],
  ['post', '/api/lessons/{lessonId}/resources'],
  ['post', '/api/orders'],
  ['post', '/api/orders/{id}/payment-proof'],
  ['patch', '/api/orders/{id}/verify'],
  ['post', '/api/orders/{id}/activate'],
  ['post', '/api/orders/{id}/cancel'],
  ['get', '/api/enrollments/me'],
  ['patch', '/api/enrollments/{id}/revoke'],
  ['post', '/api/progress'],
  ['get', '/api/progress'],
  ['get', '/api/projects'],
  ['get', '/api/projects/{slug}'],
  ['post', '/api/projects/{id}/media'],
  ['post', '/api/projects/{id}/members'],
  ['get', '/api/collective'],
  ['get', '/api/collective/{slug}'],
  ['get', '/api/marketplace'],
  ['get', '/api/marketplace/{slug}'],
  ['post', '/api/marketplace/{id}/media'],
  ['get', '/api/search'],
  ['get', '/api/admin/overview'],
  ['get', '/api/admin/users'],
  ['get', '/api/admin/orders'],
  ['post', '/api/admin/media/upload-url'],
  ['post', '/api/admin/media/confirm'],
];

describe('openapi.export (contract on docs/openapi.json)', () => {
  const doc = loadDoc();

  it('is a valid OpenAPI 3 document for the Xolvon Backend API', () => {
    expect(doc.openapi).toMatch(/^3\./);
    expect(doc.info.title).toBe('Xolvon Backend API');
    expect(typeof doc.paths).toBe('object');
  });

  it('declares the bearerAuth security scheme (DL-016, Bearer-only)', () => {
    const scheme = doc.components?.securitySchemes?.bearerAuth;
    expect(scheme).toBeDefined();
    expect(scheme?.type).toBe('http');
    expect(scheme?.scheme).toBe('bearer');
    expect(scheme?.bearerFormat).toBe('JWT');
  });

  it('serves every documented path under the /api global prefix', () => {
    const offenders = Object.keys(doc.paths).filter(
      (p) => p !== '/api' && !p.startsWith('/api/'),
    );
    expect(offenders).toEqual([]);
  });

  it('documents the required operations', () => {
    const missing = REQUIRED_OPERATIONS.filter(
      ([method, path]) => doc.paths[path]?.[method] === undefined,
    );
    expect(missing).toEqual([]);
  });

  it('covers every active controller prefix', () => {
    for (const prefix of CONTROLLER_PREFIXES) {
      const hit = Object.keys(doc.paths).some((p) =>
        prefix === '' ? p === '/api' : p.startsWith(`/api/${prefix}`),
      );
      expect(hit).toBe(true);
    }
  });

  it('contains no credential-shaped values (names may mention passwords)', () => {
    expect(findSecretLeaks(doc)).toEqual([]);
  });

  it('has no Cloudflare token or private-key material in the raw JSON text', () => {
    const raw = readFileSync(ARTIFACT_PATH, 'utf8');
    expect(raw).not.toMatch(/cfut_[A-Za-z0-9]/);
    expect(raw).not.toMatch(/BEGIN [A-Z ]*PRIVATE KEY/);
    expect(raw).not.toMatch(/password_hash/);
  });
});
